[build]
  command = "npm run build"
  publish = "."

# --- Functions (your AI generator etc) ---
[functions]
  directory = "functions"

# --- Do NOT rewrite anything under /objects or /ai-reference ---
# Ensure raw files are served as-is (no SPA fallback)

# Serve the objects folder verbatim
[[redirects]]
  from = "/objects/*"
  to = "/objects/:splat"
  status = 200
  force = true

# Serve the ai-reference folder verbatim
[[redirects]]
  from = "/ai-reference/*"
  to = "/ai-reference/:splat"
  status = 200
  force = true

# Ensure the objects manifest resolves directly
[[redirects]]
  from = "/objects/manifest.json"
  to = "/objects/manifest.json"
  status = 200
  force = true

# Your SPA fallback (kept last!)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Correct MIME so .scad renders as text in the viewer
[[headers]]
  for = "/objects/*.scad"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    X-Content-Type-Options = "nosniff"

# (Optional) also mark README/JSON as text
[[headers]]
  for = "/objects/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/objects/*/README.md"
  [headers.values]
    Content-Type = "text/markdown; charset=utf-8"
